- name: Hadrien Mary
  email: hadim@users.noreply.github.com
  alternate_emails:
  - hadrien.mary@gmail.com
  num_commits: 40
  first_commit: 2018-04-26 12:25:06
- name: Satyakam Singhal
  email: 44098427+satyakam7@users.noreply.github.com
  num_commits: 1
  first_commit: 2021-07-02 08:04:58
